# Generated by Django 4.0.3 on 2022-04-23 05:47

import UMS.models
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0004_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contactNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, validators=[django.core.validators.RegexValidator(regex='^?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, validators=[UMS.models.validate_geeks_mail]),
        ),
    ]
