# Generated by Django 4.0.3 on 2022-04-23 05:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0006_alter_profile_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contactNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
