# Generated by Django 4.0.3 on 2022-04-23 07:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0007_alter_profile_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contactNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(max_length=120, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(max_length=120, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='totalDetection',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
