# Generated by Django 4.0.3 on 2022-04-23 08:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0008_alter_profile_contactnumber_alter_profile_dp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contactNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='totalDetection',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
