# Generated by Django 4.0.3 on 2022-04-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0013_alter_profile_dp_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='totalDetection',
            field=models.IntegerField(default=0),
        ),
    ]
