# Generated by Django 4.0.3 on 2022-03-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.FileField(upload_to='')),
                ('duration', models.FloatField()),
                ('dateofUpload', models.DateField()),
                ('timeToUpload', models.TimeField()),
                ('Owner', models.CharField(max_length=50)),
                ('Tag', models.CharField(max_length=10)),
            ],
        ),
    ]
