# Generated by Django 4.0.3 on 2022-04-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EC', '0002_audio_storage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_storage',
            name='Owner',
        ),
    ]
