# Generated by Django 4.0.3 on 2022-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC', '0003_remove_audio_storage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_storage',
            name='recording',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='audio_storage',
            name='timeToUpload',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
