# Generated by Django 4.0.3 on 2022-04-24 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC', '0005_remove_audio_storage_recording_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_storage',
            name='dateofUpload',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 16, 11, 35, 745195)),
        ),
    ]
