# Generated by Django 4.0.3 on 2022-04-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC', '0007_alter_audio_storage_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_storage',
            name='audio_file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='audio_storage',
            name='dateofUpload',
            field=models.DateField(),
        ),
    ]
