# Generated by Django 4.0.3 on 2022-05-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC', '0010_alter_audio_storage_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_storage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
